# =========================================================
# 🏛 Executive Presentation Mode Engine — v7.7R
# Generates structured boardroom briefing content
# Slide-Based Tactical Command Presentation
# Fully compatible with PDF Export & Dashboard integration
# =========================================================

import pandas as pd


def generate_executive_presentation(
    portfolio_summary: dict,
    risk_df: pd.DataFrame = None,
    tactical_scores_df: pd.DataFrame = None,
    alerts_list: list = None,
    intel_brief_text: str = "",
):
    """
    Generates a structured multi-slide executive briefing.
    Returns a list of slides, each slide is:
    {
        'title': 'Slide Title',
        'content': 'Formatted text'
    }
    Designed for PDF export, future PPT conversion, or live dashboard display.
    """

    slides = []

    # ===================================================
    # Slide 1 — Cover Page
    # ===================================================
    slides.append({
        "title": "Fox Valley Tactical Command — Executive Briefing",
        "content": f"""
Fox Valley Wealth Management  
Prepared for: Board of Directors  
Generated by Fox Valley Intelligence Engine — v7.7R

Portfolio Tactical Condition: {portfolio_summary.get('avg_gain_loss_pct', 0):.2f}%
Cash Available: ${portfolio_summary.get('cash', 0):,}
Total Value: ${portfolio_summary.get('total_value', 0):,}

CONFIDENTIAL — STRATEGIC USE ONLY
"""
    })

    # ===================================================
    # Slide 2 — Executive Portfolio Overview
    # ===================================================
    slides.append({
        "title": "Executive Portfolio Overview",
        "content": f"""
Total Portfolio Value: ${portfolio_summary.get('total_value', 0):,}
Cash Reserve: ${portfolio_summary.get('cash', 0):,}
Realized/Unrealized Gain-Loss: ${portfolio_summary.get('gain_loss_total', 0):,}
Average Return: {portfolio_summary.get('avg_gain_loss_pct', 0):.2f}%

Strategic Interpretation:
• Portfolio maintains stable tactical posture
• Cash flexibility intact for strategic opportunities
• Exposure levels acceptable under current volatility regime
"""
    })

    # ===================================================
    # Slide 3 — Risk Heatmap
    # ===================================================
    if risk_df is not None and not risk_df.empty:
        slides.append({
            "title": "Risk Posture & Exposure",
            "content": """
Top Risk & Exposure Alignment:

""" + risk_df.to_string(index=False)
        })
    else:
        slides.append({
            "title": "Risk Posture & Exposure",
            "content": "No critical or elevated risk flags at this time."
        })

    # ===================================================
    # Slide 4 — Tactical Scoring Insights
    # ===================================================
    if tactical_scores_df is not None and not tactical_scores_df.empty:
        slides.append({
            "title": "Tactical Scoring — Strategic Prioritization",
            "content": """
Top Tactical Priority Rankings:

""" + tactical_scores_df.to_string(index=False) + """
Interpretation:
• High-score positions suitable for Buy/Trim opportunities
• Low-score positions require caution or tightening stops
"""
        })
    else:
        slides.append({
            "title": "Tactical Scoring Insights",
            "content": "No tactical scoring data available."
        })

    # ===================================================
    # Slide 5 — Tactical Alerts
    # ===================================================
    alerts_text = "\n".join(alerts_list) if alerts_list else "No tactical alerts triggered."
    
    slides.append({
        "title": "🚨 Tactical Alerts — Prioritized Actions",
        "content": alerts_text
    })

    # ===================================================
    # Slide 6 — Intelligence Brief Narrative
    # ===================================================
    slides.append({
        "title": "Strategic Intelligence Brief",
        "content": intel_brief_text or "No Intelligence Brief available."
    })

    # ===================================================
    # Slide 7 — Command Recommendations
    # ===================================================
    slides.append({
        "title": "Command-Level Recommendations",
        "content": """
Recommended Tactical Actions:

• Review Rank 1 Zacks Opportunities
• Tighten stops on underperformers
• Trim overweight high-risk positions
• Maintain liquidity for opportunity shots
• Monitor alert-tracked assets daily
"""
    })

    # ===================================================
    # Slide 8 — Executive Authorization
    # ===================================================
    slides.append({
        "title": "Authorization Panel",
        "content": """
Fox Valley Tactical Command Briefing

Authorized Officer: _________________________  
Tactical Execution Approval:  ☐ Yes   ☐ No

Signature: _________________________
Date: _____________________________

Board of Directors Review Required:
☐ Immediate  
☐ In Next Scheduled Meeting
"""
    })

    return slides
