# =========================================================
# 🏛 Executive Presentation Mode Engine — v7.7R-BOD
# Converts tactical intelligence into structured slide format
# Compatible with Command Report, BOD Briefing, and PDF Engines
# =========================================================

def generate_executive_presentation(
    portfolio_summary: dict,
    risk_df,
    tactical_scores_df,
    alerts_list,
    intel_brief_text: str,
):
    """
    Generates structured presentation 'slides' as sections of text.
    Intended for PDF export, PPT future build, or Streamlit slide mode.
    Returns list of slides, each slide is a dict: {title, content}
    """

    slides = []

    # ===================================================
    # Slide 1 — Executive Cover
    # ===================================================
    slides.append({
        "title": "Fox Valley Tactical Command Briefing",
        "content": f"""
Fox Valley Wealth Management — Executive Briefing
Generated by Fox Valley Intelligence Engine — v7.7R

Prepared for: Board of Directors
Portfolio Tactical Condition: {portfolio_summary.get('avg_gain_loss_pct', ''):.2f}% Avg Return
Cash Available: ${portfolio_summary.get('cash', 0):,}

Approval Level: Confidential | Strategic Decision Support
"""
    })

    # ===================================================
    # Slide 2 — Executive Overview
    # ===================================================
    slides.append({
        "title": "Executive Overview — Portfolio Condition",
        "content": f"""
Total Portfolio Value: ${portfolio_summary.get('total_value', 0):,}
Cash Allocation: ${portfolio_summary.get('cash', 0):,}
Total Gain/Loss: ${portfolio_summary.get('gain_loss_total', 0):,}
Average Gain/Loss %: {portfolio_summary.get('avg_gain_loss_pct', 0):.2f}%

Strategic Posture:
• Tactical condition remains stable
• Active risk exposure is manageable
• Zacks Screen intelligence synchronized
"""
    })

    # ===================================================
    # Slide 3 — Risk Posture
    # ===================================================
    slides.append({
        "title": "Risk Posture & Exposure Heatmap",
        "content": """
Below is the tactical risk alignment based on trailing stop distance,
volatility class, and position exposure weighting:

""" + risk_df.to_string(index=False)
    })

    # ===================================================
    # Slide 4 — Tactical Scoring Insights
    # ===================================================
    slides.append({
        "title": "Tactical Priority — Scoring Insights",
        "content": """
Strategic Score Rankings (High → Low Priority):

""" + tactical_scores_df.to_string(index=False) + """
Interpretation:
• High-score positions may qualify for Buy/Trim Candidates
• Low scores may need trailing stop tightening or review
"""
    })

    # ===================================================
    # Slide 5 — Tactical Alerts
    # ===================================================
    alerts_text = "\n".join(alerts_list) if alerts_list else "No high-priority tactical alerts at this time."
    slides.append({
        "title": "🚨 Tactical Alerts — Priority Action Required",
        "content": alerts_text
    })

    # ===================================================
    # Slide 6 — Intelligence Brief Narrative
    # ===================================================
    slides.append({
        "title": "Strategic Intelligence Brief",
        "content": intel_brief_text
    })

    # ===================================================
    # Slide 7 — Command-Level Recommendations
    # ===================================================
    slides.append({
        "title": "Command Recommendations",
        "content": """
Recommended Tactical Considerations:

• Review Rank 1 Candidates for entering positions
• Assess trailing stop levels on all critical holdings
• Identify overexposed positions—prepare trim candidates
• Maintain strategic liquidity alignment
"""
    })

    # ===================================================
    # Slide 8 — Authorization Page
    # ===================================================
    slides.append({
        "title": "Authorization & Delegation",
        "content": """
Executive Authorization Panel
-----------------------------------------
Prepared for: Fox Valley Wealth Board
Authorized Tactical Officer: _____________
Execution Approval:        ☐ Yes   ☐ No

Signature: ___________________
Date: ________________________
"""
    })

    return slides
