from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch


# =========================================================
# 📄 PDF Export Engine — v7.7R Final Deployment
# Converts Command Report text into clean, printable PDF
# =========================================================

def export_report_to_pdf(
    report_text: str,
    filename: str = "Fox_Valley_Tactical_Command_Report.pdf"
):
    """
    Converts the fully-generated Command Report text
    into a clean PDF document using ReportLab.

    Parameters:
        report_text: Full narrative text from Command Report Builder
        filename: Desired PDF filename (default: Tactical Report)
    Returns:
        The filename of the saved PDF
    """

    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter

    # Standard tactical margins
    x_margin = inch * 0.75
    y_margin = inch * 0.75

    y_position = height - y_margin

    # Report header
    c.setFont("Helvetica-Bold", 14)
    c.drawString(x_margin, y_position, "Fox Valley Tactical Command Report — v7.7R")
    y_position -= 25

    c.setFont("Helvetica", 10)
    c.drawString(x_margin, y_position, "Generated by Fox Valley Intelligence Engine")
    y_position -= 30

    # Main body text
    c.setFont("Helvetica", 9)
    lines = report_text.split("\n")

    for line in lines:
        if y_position <= y_margin:
            c.showPage()
            c.setFont("Helvetica", 9)
            y_position = height - y_margin
        c.drawString(x_margin, y_position, line)
        y_position -= 12  # Line spacing

    c.save()
    return filename
