from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from datetime import datetime


# =========================================================
# 📑 PDF Export Engine — Executive Briefing Format (v7.7R-BOD)
# Creates branded, board-ready executive tactical briefing PDF
# =========================================================

def export_report_to_pdf(
    report_text: str,
    filename: str = "Fox_Valley_Executive_Tactical_Briefing.pdf"
):
    """
    Converts Command Report into a formal Board of Directors PDF.
    Includes branding, section headers, signature-ready footer.
    """

    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter

    # Define standard executive margins
    x_margin = inch * 0.75
    y_margin = inch * 0.75
    y_pos = height - y_margin

    # =========================================================
    # COVER HEADER — BRANDING
    # =========================================================
    c.setFont("Helvetica-Bold", 16)
    c.drawString(x_margin, y_pos, "Fox Valley Wealth Management")
    y_pos -= 25

    c.setFont("Helvetica", 12)
    c.drawString(x_margin, y_pos, "Executive Tactical Command Briefing")
    y_pos -= 30

    c.setFont("Helvetica-Oblique", 10)
    c.drawString(x_margin, y_pos, "Generated by Fox Valley Intelligence Engine — v7.7R")
    y_pos -= 30

    date_stamp = datetime.now().strftime("%B %d, %Y — %I:%M %p")
    c.setFont("Helvetica", 9)
    c.drawString(x_margin, y_pos, f"Report Date: {date_stamp}")
    y_pos -= 40

    # Divider line
    c.line(x_margin, y_pos, width - x_margin, y_pos)
    y_pos -= 30

    # =========================================================
    # EXECUTIVE SUMMARY BLOCK
    # =========================================================
    c.setFont("Helvetica-Bold", 12)
    c.drawString(x_margin, y_pos, "📌 Executive Summary")
    y_pos -= 25

    c.setFont("Helvetica", 9)
    summary_lines = [
        "This Tactical Command Briefing provides a structured assessment of",
        "portfolio performance, risk exposure, Zacks-driven opportunity insights,",
        "and tactical decision guidance for the Board of Directors.",
        "",
        "The following document is structured for strategic review,",
        "with risk posture, ranking insights, tactical scoring, and alerts included."
    ]

    for line in summary_lines:
        c.drawString(x_margin, y_pos, line)
        y_pos -= 12

    y_pos -= 20
    c.line(x_margin, y_pos, width - x_margin, y_pos)
    y_pos -= 30

    # =========================================================
    # MAIN REPORT BODY
    # =========================================================
    c.setFont("Helvetica-Bold", 12)
    c.drawString(x_margin, y_pos, "📄 Tactical Command Report")
    y_pos -= 25

    c.setFont("Helvetica", 9)

    lines = report_text.split("\n")
    for line in lines:
        if y_pos < y_margin:
            c.showPage()
            y_pos = height - y_margin
            c.setFont("Helvetica", 9)
        c.drawString(x_margin, y_pos, line)
        y_pos -= 12

    # =========================================================
    # SIGNATURE FOOTER — BOD READY
    # =========================================================
    c.showPage()
    c.setFont("Helvetica-Bold", 14)
    c.drawString(x_margin, height - 100, "Fox Valley Tactical Command — Executive Certification")
    c.setFont("Helvetica", 9)
    c.drawString(x_margin, height - 130, "Prepared for: Board of Directors")
    c.drawString(x_margin, height - 150, "Authorized by: Fox Valley Wealth Management Tactical Intelligence Division")
    c.drawString(x_margin, height - 200, "______________________________")
    c.drawString(x_margin, height - 215, "Executive Officer Signature")
    c.save()

    return filename
